repos:
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
    additional_dependencies:
    - pandas-stubs
    - pytest
    - requests-cache
    - requests-mock
    - types-Jinja2
    - types-lxml
    - types-python-dateutil
    - types-PyYAML
    - types-requests
    args: []
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.1
  hooks:
  - id: ruff
  - id: ruff-format
    args: [ --check ]
