name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Upgrade pip, wheel
      run: |
        python -m pip install --upgrade pip wheel
        # Locate pip cache directory
        echo "pip-cache-dir=$(pip cache dir)" >> $GITHUB_ENV

    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ${{ env.pip-cache-dir }}
        key: ubuntu-latest

    - name: Check "black" code style
      run: |
        pip install black
        black --check .

    - name: Lint with flake8 & isort
      run: |
        pip install flake8 isort
        flake8 --count --max-complexity=27 --show-source --statistics
        isort --check-only .
